// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3cmfUUhA8iNtTnUoLWbZBN6vBdw6a13M',
    appId: '1:38854833849:web:12e2731a59fc2bade44d68',
    messagingSenderId: '38854833849',
    projectId: 'terrarium-i',
    authDomain: 'terrarium-i.firebaseapp.com',
    storageBucket: 'terrarium-i.appspot.com',
    measurementId: 'G-Z7RBG6CWGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2MRoAXH2QJNgTB2sgMUT0tkj6kgnPBw',
    appId: '1:38854833849:android:511ef15bbb975085e44d68',
    messagingSenderId: '38854833849',
    projectId: 'terrarium-i',
    storageBucket: 'terrarium-i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfVDp2jeaujhz3Cn3pRnQc9L5a17lwHQg',
    appId: '1:38854833849:ios:710ef0ed284ecc3ee44d68',
    messagingSenderId: '38854833849',
    projectId: 'terrarium-i',
    storageBucket: 'terrarium-i.appspot.com',
    iosClientId: '38854833849-hlvtj3e8t96iqpi5b0vm4f21i0mn2eqs.apps.googleusercontent.com',
    iosBundleId: 'com.vqh2602.terrarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfVDp2jeaujhz3Cn3pRnQc9L5a17lwHQg',
    appId: '1:38854833849:ios:710ef0ed284ecc3ee44d68',
    messagingSenderId: '38854833849',
    projectId: 'terrarium-i',
    storageBucket: 'terrarium-i.appspot.com',
    iosClientId: '38854833849-hlvtj3e8t96iqpi5b0vm4f21i0mn2eqs.apps.googleusercontent.com',
    iosBundleId: 'com.vqh2602.terrarium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3cmfUUhA8iNtTnUoLWbZBN6vBdw6a13M',
    appId: '1:38854833849:web:df89f58852e95ae2e44d68',
    messagingSenderId: '38854833849',
    projectId: 'terrarium-i',
    authDomain: 'terrarium-i.firebaseapp.com',
    storageBucket: 'terrarium-i.appspot.com',
    measurementId: 'G-MJ89WCGVRS',
  );
}
